# Generated by Django 3.2.9 on 2021-12-04 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandName', models.CharField(max_length=100)),
                ('bandDescription', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueName', models.CharField(max_length=100)),
                ('venueDescription', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('venueEmail', models.EmailField(max_length=254)),
                ('venuePhone', models.IntegerField()),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('media', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Band', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Venue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
