# Generated by Django 3.2.9 on 2021-12-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BandView', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
