# Generated by Django 3.2.9 on 2021-12-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BandView', '0002_remove_band_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='profilePic',
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
