# Generated by Django 3.2.9 on 2021-12-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BandView', '0011_auto_20211208_1255'),
        ('BandView', '0012_auto_20211208_2156'),
    ]

    operations = [
    ]
