# Generated by Django 3.2.9 on 2021-12-07 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BandView', '0006_auto_20211206_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
