# Generated by Django 3.2.9 on 2021-12-08 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BandView', '0008_auto_20211206_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('event_band', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BandView.band')),
                ('event_venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BandView.venue')),
            ],
        ),
    ]
