# Generated by Django 3.2.9 on 2021-12-09 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BandView', '0010_auto_20211207_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BandView.band'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BandView.venue'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(),
        ),
    ]
